-- MySQL Script generated by MySQL Workbench
-- czw, 5 lis 2020, 18:36:00
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema wiktor_baza
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `user` ;

CREATE TABLE IF NOT EXISTS `user` (
  `id` INT(6) UNSIGNED NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(255) NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `surname` VARCHAR(255) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = MEMORY;


-- -----------------------------------------------------
-- Table `chat`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `chat` ;

CREATE TABLE IF NOT EXISTS `chat` (
  `id` INT(6) UNSIGNED NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `user_chat`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `user_chat` ;

CREATE TABLE IF NOT EXISTS `user_chat` (
  `user_id` INT(6) UNSIGNED NOT NULL,
  `chat_id` INT(6) UNSIGNED NOT NULL,
  UNIQUE INDEX `user_job_id` USING BTREE (`user_id`, `chat_id`),
  PRIMARY KEY (`user_id`, `chat_id`),
  CONSTRAINT `fk_user_chat_1`
    FOREIGN KEY (`user_id`)
    REFERENCES `user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_chat_2`
    FOREIGN KEY (`chat_id`)
    REFERENCES `chat` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `message`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `message` ;

CREATE TABLE IF NOT EXISTS `message` (
  `id` INT(6) UNSIGNED NOT NULL,
  `text` VARCHAR(255) NOT NULL,
  `created_at` DATETIME NOT NULL,
  `chat_id` INT(6) UNSIGNED NOT NULL,
  `user_id` INT(6) UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_message_1_idx` (`user_id` ASC),
  INDEX `fk_message_2_idx` (`chat_id` ASC),
  CONSTRAINT `fk_message_1`
    FOREIGN KEY (`user_id`)
    REFERENCES `user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_message_2`
    FOREIGN KEY (`chat_id`)
    REFERENCES `chat` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
